# Use this workspace to collaborate
workspace:
  id: 74ec7dc4-a27d-4969-82a1-25f209fff2aa

# All resources in the `postman/` folder are automatically registered in Local View.
# Point to additional files outside the `postman/` folder to register them individually. Example:
#localResources:
#  collections:
#    - ../tests/E2E Test Collection/
